
import { Movie } from './types';

export const MOVIES: Movie[] = [
  // --- TV SHOWS ---
  {
    id: 'tv-1',
    title: 'Stranger Things',
    year: 2016,
    rating: 8.7,
    seasons: 4,
    type: 'tv',
    genres: ['Drama', 'Sci-Fi', 'Horror'],
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    posterUrl: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1533107862482-0e6974b06ec4?q=80&w=1920&auto=format&fit=crop',
    director: 'The Duffer Brothers',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    aiScore: 98,
    aiInsight: 'A masterful blend of 80s nostalgia and genuine cosmic horror.'
  },
  {
    id: 'tv-2',
    title: 'Wednesday',
    year: 2022,
    rating: 8.1,
    seasons: 1,
    type: 'tv',
    genres: ['Comedy', 'Crime', 'Fantasy'],
    description: 'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.',
    posterUrl: 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1920&auto=format&fit=crop',
    director: 'Tim Burton',
    cast: ['Jenna Ortega', 'Gwendoline Christie', 'Christina Ricci'],
    aiScore: 92,
    aiInsight: 'Jenna Ortega revitalizes the character with a sharp, contemporary edge.'
  },
  {
    id: 'tv-3',
    title: 'Money Heist',
    year: 2017,
    rating: 8.2,
    seasons: 5,
    type: 'tv',
    genres: ['Action', 'Crime', 'Drama'],
    description: 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.',
    posterUrl: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1920&auto=format&fit=crop',
    director: 'Alex Pina',
    cast: ['Ursula Corbero', 'Alvaro Morte', 'Itziar Ituno'],
    aiScore: 94,
    aiInsight: 'A high-stakes chess match played out in the streets of Madrid.'
  },
  {
    id: 'tv-4',
    title: 'Sacred Games',
    year: 2018,
    rating: 8.5,
    seasons: 2,
    type: 'tv',
    genres: ['Action', 'Crime', 'Drama'],
    description: 'A link in their pasts leads an honest cop to a fugitive gang lord, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.',
    posterUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?q=80&w=1920&auto=format&fit=crop',
    director: 'Anurag Kashyap',
    cast: ['Saif Ali Khan', 'Nawazuddin Siddiqui', 'Pankaj Tripathi'],
    aiScore: 96,
    aiInsight: 'The definitive Indian noir series that paved the way for streaming in India.'
  },
  {
    id: 'tv-5',
    title: 'The Witcher',
    year: 2019,
    rating: 8.0,
    seasons: 3,
    type: 'tv',
    genres: ['Action', 'Adventure', 'Fantasy'],
    description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
    posterUrl: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1920&auto=format&fit=crop',
    director: 'Lauren Schmidt Hissrich',
    cast: ['Henry Cavill', 'Anya Chalotra', 'Freya Allan'],
    aiScore: 89,
    aiInsight: 'Gritty high fantasy with a compelling central performance by Henry Cavill.'
  },
  {
    id: 'tv-6',
    title: 'Squid Game',
    year: 2021,
    rating: 8.0,
    seasons: 1,
    type: 'tv',
    genres: ['Action', 'Drama', 'Thriller'],
    description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    posterUrl: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1920&auto=format&fit=crop',
    director: 'Hwang Dong-hyuk',
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'HoYeon Jung'],
    aiScore: 95,
    aiInsight: 'A brutal social critique disguised as a heart-pounding survival thriller.'
  },
  {
    id: 'tv-7',
    title: 'The Crown',
    year: 2016,
    rating: 8.6,
    seasons: 6,
    type: 'tv',
    genres: ['Biography', 'Drama', 'History'],
    description: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.',
    posterUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1513438205128-16af16280739?q=80&w=1920&auto=format&fit=crop',
    director: 'Peter Morgan',
    cast: ['Claire Foy', 'Olivia Colman', 'Imelda Staunton'],
    aiScore: 93,
    aiInsight: 'Lush production values and unparalleled acting make this a historical gem.'
  },
  {
    id: 'tv-8',
    title: 'Bridgerton',
    year: 2020,
    rating: 7.4,
    seasons: 3,
    type: 'tv',
    genres: ['Drama', 'Romance'],
    description: 'Wealth, lust, and betrayal set against the backdrop of Regency-era England, seen through the eyes of the powerful Bridgerton family.',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=1920&auto=format&fit=crop',
    director: 'Chris Van Dusen',
    cast: ['Nicola Coughlan', 'Luke Newton', 'Jonathan Bailey'],
    aiScore: 87,
    aiInsight: 'A vibrant, modern take on period drama that captivates with every scandal.'
  },
  {
    id: 'tv-9',
    title: 'Dark',
    year: 2017,
    rating: 8.7,
    seasons: 3,
    type: 'tv',
    genres: ['Crime', 'Drama', 'Mystery'],
    description: 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.',
    posterUrl: 'https://images.unsplash.com/photo-1509193072711-d3a36280003b?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bc1b?q=80&w=1920&auto=format&fit=crop',
    director: 'Baran bo Odar',
    cast: ['Louis Hofmann', 'Karoline Eichhorn', 'Lisa Vicari'],
    aiScore: 99,
    aiInsight: 'The most intricate time-travel narrative ever committed to screen.'
  },
  {
    id: 'tv-10',
    title: 'Heeramandi: The Diamond Bazaar',
    year: 2024,
    rating: 6.9,
    seasons: 1,
    type: 'tv',
    genres: ['Drama', 'History', 'Romance'],
    description: 'The arch-rivals Mallikajaan and Fareedan are locked in a battle of succession of Heeramandi, where courtesans are queens.',
    posterUrl: 'https://images.unsplash.com/photo-1589118949245-7d38baf380d6?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1524492459413-5bc50b55509a?q=80&w=1920&auto=format&fit=crop',
    director: 'Sanjay Leela Bhansali',
    cast: ['Manisha Koirala', 'Sonakshi Sinha', 'Aditi Rao Hydari'],
    aiScore: 91,
    aiInsight: 'Bhansali\'s opulence translates beautifully to the small screen with poetic grandeur.'
  },

  // --- MOVIES ---
  {
    id: 'm-1',
    title: 'RRR',
    year: 2022,
    rating: 7.8,
    duration: '3h 7min',
    type: 'movie',
    genres: ['Action', 'Drama'],
    description: 'A fearless revolutionary and an officer in the British force, who are also friends, decide to join forces and chart a path to freedom.',
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=1920&auto=format&fit=crop',
    director: 'S.S. Rajamouli',
    cast: ['N.T. Rama Rao Jr.', 'Ram Charan', 'Alia Bhatt'],
    aiScore: 97,
    aiInsight: 'A maximalist action masterpiece that redefined the global perception of Indian cinema.'
  },
  {
    id: 'm-2',
    title: 'Society of the Snow',
    year: 2023,
    rating: 7.8,
    duration: '2h 24min',
    type: 'movie',
    genres: ['Drama', 'Adventure', 'History'],
    description: 'The flight of a rugby team crashes onto a glacier in the heart of the Andes. The survivors find themselves in one of the world\'s toughest environments.',
    posterUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?q=80&w=1920&auto=format&fit=crop',
    director: 'J.A. Bayona',
    cast: ['Enzo Vogrincic', 'Agustín Pardella', 'Matías Recalt'],
    aiScore: 94,
    aiInsight: 'A harrowing yet deeply spiritual testament to the human will to survive.'
  },
  {
    id: 'm-3',
    title: 'Extraction 2',
    year: 2023,
    rating: 7.0,
    duration: '2h 3min',
    type: 'movie',
    genres: ['Action', 'Thriller'],
    description: 'Back from the brink of death, highly skilled commando Tyler Rake embarks on another dangerous mission.',
    posterUrl: 'https://images.unsplash.com/photo-1509193072711-d3a36280003b?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1509193072711-d3a36280003b?q=80&w=1920&auto=format&fit=crop',
    director: 'Sam Hargrave',
    cast: ['Chris Hemsworth', 'Golshifteh Farahani', 'Adam Bessa'],
    aiScore: 82,
    aiInsight: 'A masterclass in modern stunt-work and kinetic action choreography.'
  },
  {
    id: 'm-4',
    title: 'Animal',
    year: 2023,
    rating: 6.2,
    duration: '3h 21min',
    type: 'movie',
    genres: ['Action', 'Crime', 'Drama'],
    description: 'A son\'s obsessive love for his father leads to a violent, dark journey of revenge and destruction.',
    posterUrl: 'https://images.unsplash.com/photo-1589487391730-58f20eb2c308?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1508138221679-760a23a2285b?q=80&w=1920&auto=format&fit=crop',
    director: 'Sandeep Reddy Vanga',
    cast: ['Ranbir Kapoor', 'Anil Kapoor', 'Rashmika Mandanna'],
    aiScore: 78,
    aiInsight: 'A polarizing, visceral study of toxic masculinity and unbridled vengeance.'
  },
  {
    id: 'm-5',
    title: 'Glass Onion',
    year: 2022,
    rating: 7.1,
    duration: '2h 19min',
    type: 'movie',
    genres: ['Comedy', 'Crime', 'Drama'],
    description: 'Famed Southern detective Benoit Blanc travels to Greece for his latest case involving a group of wealthy friends.',
    posterUrl: 'https://images.unsplash.com/photo-1585647347384-2593bc35786b?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=1920&auto=format&fit=crop',
    director: 'Rian Johnson',
    cast: ['Daniel Craig', 'Edward Norton', 'Janelle Monáe'],
    aiScore: 88,
    aiInsight: 'A sharp, colorful satire that deconstructs the whodunit genre with wit.'
  },
  {
    id: 'm-6',
    title: 'Leo',
    year: 2023,
    rating: 7.2,
    duration: '2h 44min',
    type: 'movie',
    genres: ['Action', 'Crime', 'Thriller'],
    description: 'A mild-mannered cafe owner becomes a local hero, but old secrets from his past come back to haunt him.',
    posterUrl: 'https://images.unsplash.com/photo-1585671146633-90d562f689f1?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1470219559762-187157327644?q=80&w=1920&auto=format&fit=crop',
    director: 'Lokesh Kanagaraj',
    cast: ['Thalapathy Vijay', 'Sanjay Dutt', 'Arjun Sarja'],
    aiScore: 86,
    aiInsight: 'Stylized action that cements the Lokesh Cinematic Universe as a force to be reckoned with.'
  },
  {
    id: 'm-7',
    title: 'Nimona',
    year: 2023,
    rating: 7.5,
    duration: '1h 41min',
    type: 'movie',
    genres: ['Animation', 'Adventure'],
    description: 'A knight framed for a crime he didn\'t commit teams up with a shapeshifting teen to prove his innocence.',
    posterUrl: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1920&auto=format&fit=crop',
    director: 'Nick Bruno',
    cast: ['Chloe Grace Moretz', 'Riz Ahmed'],
    aiScore: 91,
    aiInsight: 'Vibrant, rebellious, and deeply moving animation with a powerful message.'
  },
  {
    id: 'm-8',
    title: 'Jaane Jaan',
    year: 2023,
    rating: 7.0,
    duration: '2h 19min',
    type: 'movie',
    genres: ['Crime', 'Drama', 'Mystery'],
    description: 'A single mother and her daughter are caught in a crime, and their neighbor, a talented math teacher, offers to help them cover it up.',
    posterUrl: 'https://images.unsplash.com/photo-1512070679279-8988d32161be?q=80&w=800&auto=format&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=1920&auto=format&fit=crop',
    director: 'Sujoy Ghosh',
    cast: ['Kareena Kapoor Khan', 'Jaideep Ahlawat', 'Vijay Varma'],
    aiScore: 89,
    aiInsight: 'A cold, calculating thriller that showcases career-best performances from its leads.'
  }
];
